### ISSUE TITLE
Add missing README

### ISSUE THREAD

**Issue by astares** [badetitou/PharoNativeNotification#1]
Maybe you add a README and mention that the **New-BurntToastNotification** might not be available as PS 
module. Then one needs:

```
 Install-Module BurntToast
```
to install it first

**Comment by badetitou** [comment]
Thanks for the reminder

I updated the code to remove the dependency to `BurntToast`.
I still have to write the readme

**Comment by badetitou** [comment]
Readme added

**Comment by astares** [comment]
Thanks!
